<?php
/**
 * @file
 *
 * Provides functionality for entities.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function xhn_entities_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'eck' && $plugin_type == 'property_behavior') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_eck_property_types().
 */
function xhn_entities_eck_property_types() {
  return [
    'boolean' => t('Boolean'),
    'date' => t('Date'),
    'integer' => t('Integer'),
    'long_text' => t('Long text'),
  ];
}

/**
 * Implements hook_eck_property_type_schema_alter().
 */
function xhn_entities_eck_property_type_schema_alter(&$schema, $type) {
  switch ($type) {
    case 'boolean':
      $schema = [
        'description' => 'Boolean',
        'type' => 'int',
        'size' => 'tiny',
      ];
      break;

    case 'date':
      $schema = [
        'description' => 'Date',
        'type' => 'varchar',
        'length' => 10,
      ];
      break;

    case 'integer':
      $schema = [
        'description' => 'Integer',
        'type' => 'varchar',
        'length' => 20,
      ];
      break;

    case 'long_text':
      $schema = [
        'description' => 'Long text',
        'type' => 'text',
        'size' => 'normal',
      ];
      break;
  }
}

/**
 * Implements hook_entity_property_widget_alter().
 */
function xhn_entities_entity_property_widget_alter($widget, $bundle, $property) {
  switch ($bundle) {
    case 'item':
      switch ($property) {
        case 'category':
          $widget['#options'] = [
            'artifact' => 'Артефакт',
            'potion' => 'Зелье',
            'scroll' => 'Свиток',
            'other' => 'Другое',
          ];
          $widget['#default_value'] = 'artifact';
          break;

        case 'weight_in_shop':
          $range = range(1, 12);
          $widget['#options'] = array_combine($range, $range);
          break;
      }
      break;
  }

  return $widget;
}

/**
 * Implements hook_form_alter().
 *
 * {@inheritdoc}
 */
function xhn_entities_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'eck__entity__form_edit_item_item':
      // Set text format Full html as default.
      $form['field_description'][LANGUAGE_NONE][0]['#format'] = 'full_html';
      // Remove unnecessary text format field's help fieldset.
      $form['field_description'][LANGUAGE_NONE][0]['#after_build'] = [
        'xhn_entities_text_format_clearer',
      ];
      break;
  }
}

/**
 * Remove unnecessary text format field's helper fieldset.
 *
 * @param $element
 *
 * @return mixed
 */
function xhn_entities_text_format_clearer($element) {
  unset($element['format']);
  return $element;
}
