<?php
/**
 * @file
 * xhn_taxonomy_shop.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function xhn_taxonomy_shop_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Башня',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'cb9301c1-7709-4cc2-8d0c-de95347a57e0',
    'vocabulary_machine_name' => 'shop',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Древо вечности',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'e9b85dd3-74ec-4443-a60a-ee6d0d12c699',
    'vocabulary_machine_name' => 'shop',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Кузница',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '030516c7-8a34-4a44-bb61-066be7128efb',
    'vocabulary_machine_name' => 'shop',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Лавка гоблина',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 3,
    'uuid' => 'c35ee3bb-dffe-48da-9364-88578608f154',
    'vocabulary_machine_name' => 'shop',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Лунный колодец',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 4,
    'uuid' => '29f48467-18a7-4601-aef4-0506658dfa81',
    'vocabulary_machine_name' => 'shop',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Мастерская гоблинов',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 5,
    'uuid' => 'df8edd3b-e86a-4152-bcb6-557ccb353ab5',
    'vocabulary_machine_name' => 'shop',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Обитель духов',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 6,
    'uuid' => 'b41ed9c9-cbf9-4728-bc85-3eafccb08bb5',
    'vocabulary_machine_name' => 'shop',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Обсерватория',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 7,
    'uuid' => '71d92dfd-c38d-43d1-8601-aa45bfe60bb5',
    'vocabulary_machine_name' => 'shop',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Призрак',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 8,
    'uuid' => 'f406095d-1e1f-4fb0-b384-84125024b00e',
    'vocabulary_machine_name' => 'shop',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Светлячок',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 9,
    'uuid' => '22657cfd-88f4-47c0-82e2-57c75c55f03a',
    'vocabulary_machine_name' => 'shop',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  $terms[] = array(
    'name' => 'Ящик Пандоры',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 10,
    'uuid' => 'd5c88cc7-d3e5-490f-9714-8b1ccf2b1b61',
    'vocabulary_machine_name' => 'shop',
    'path' => array(
      'pathauto' => 1,
    ),
  );
  return $terms;
}
